# Trigger this workflow on release
on:
  release:
    types: [published]

# Make sure the GITHUB_TOKEN has permission to upload to our releases

jobs:
  build:
    runs-on: [windows-latest, ubuntu-latest]
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0


    - name: Install poetry
      run: |
        python -m pip install poetry==1.7.1

    - name: Configure poetry
      run: |
        python -m poetry config virtualenvs.in-project true

    - name: 'Install'
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install gh

    - name: Cache the virtualenv
      uses: actions/cache@v2
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      run: |
        python -m poetry install

    - name: 'ðŸ“¦ Build Executables'
      run: |
        cd ${{github.workspace}}
        python -m poetry run pyinstaller -n redact --onefile src/redact_cli/redact.py
        zip -r redact-${{ runner.os }}-${{ runner.arch }}.zip dist/credact -j
        gh release upload ${{github.event.release.tag_name}} redact-${{ runner.os }}-${{ runner.arch }}.zip        
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
